language: node_js
node_js: 14
before_install:
  - cp -rf src/env/index.prod.ts src/env/index.ts
script:
  - yarn run build
  - yarn run lint
  - yarn run test
deploy:
  provider: surge
  project: build
  domain: pytime.tk
  on:
    branch: master
