language: node_js
node_js: 14
jobs:
  include:
    - stage: test
      script:
        - yarn run build
        - yarn run lint
        - yarn run test
deploy:
  provider: surge
  project: web/src/build
  domain: beneficial-tray.surge.sh
